image: alpine:latest

variables:
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG

stages:
  - build
#   - deploy

build:
  stage: build
  only:
    - master
    - staging
  tags:
    - build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    # building app client
    - if [ $CI_APPLICATION_TAG == "master" ]; then APP_ENV=production; else APP_ENV=staging; fi
    - docker build --tag $CI_APPLICATION_REPOSITORY/client:$CI_APPLICATION_TAG --tag $CI_APPLICATION_REPOSITORY/client:latest --build-arg APP_ENV=$APP_ENV .
    - docker push $CI_APPLICATION_REPOSITORY/client:$CI_APPLICATION_TAG

deploy:
   stage: deploy
   only:
     - master
     - staging
   tags:
     - docker
   before_script:
     - apk update && apk upgrade
     - apk add curl
   script:
     - curl -X POST -F token=$DEPLOY_TOKEN
       -F ref=$CI_APPLICATION_TAG
       -F "variables[PROJECT_NAME]=$CI_PROJECT_NAME"
       -F "variables[COMMIT_MESSAGE]=$CI_COMMIT_MESSAGE"
       -F "variables[COMMIT_SHA]=$CI_COMMIT_SHORT_SHA"
       https://gitlab.com/api/v4/projects/22226909/trigger/pipeline
